2025-07-25 18:31:16,779 - my_app - ERROR - SQL execution failed: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank FROM `list_of_languages_by_time_of_extinction_0` GROUP BY `region`) AS T WH' at line 1")
[SQL: SELECT T.rank FROM (SELECT `region`, RANK() OVER (ORDER BY COUNT(*) DESC) AS rank FROM `list_of_languages_by_time_of_extinction_0` GROUP BY `region`) AS T WHERE T.region = 'Santa Rosa, California']
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-25 21:04:30,005 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'elevation' in 'field list'")
[SQL: SELECT `elevation` FROM `list_of_parks_in_seoul_0` WHERE `park` = 'Hwangudan Park']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-25 21:32:53,617 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'score' in 'order clause'")
[SQL: SELECT `player` FROM `list_of_oldest_and_y_d43380ce` ORDER BY `score` DESC LIMIT 20]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-25 22:03:56,364 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'division' in 'field list'")
[SQL: SELECT `division` FROM `list_of_major_league_baseball_franchise_postseason_droughts_2` WHERE `team` = 'New York Yankees']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 00:10:19,580 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'birth_date' in 'field list'")
[SQL: SELECT `birth_date` FROM `t_1999_european_grand_prix_0` WHERE `driver` = 'Luca Badoer']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 00:18:55,430 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'birth_date' in 'field list'")
[SQL: SELECT `birth_date` FROM `list_of_doping_cases_in_athletics_2` WHERE `name` = 'VÃ­ctor Castillo']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 00:45:00,723 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'birthday' in 'field list'")
[SQL: SELECT `birthday` FROM `list_of_new_york_rangers_draft_picks_0` WHERE `player` = 'Syl Apps';]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 03:12:43,040 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1525, "Incorrect DATETIME value: '1:15.643'")
[SQL: SELECT `driver` FROM `t_1992_hungarian_grand_prix_0` WHERE `lap` = '1:15.643']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 03:13:23,214 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1525, "Incorrect DATETIME value: '1:15.643'")
[SQL: SELECT `driver` FROM `t_1992_hungarian_grand_prix_0` WHERE `lap` = '1:15.643']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 04:32:37,879 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'main_actors' in 'field list'")
[SQL: SELECT `main_actors` FROM `list_of_french_language_films_7` WHERE `english_title` = 'The Last Metro']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 04:54:13,400 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'age' in 'field list'")
[SQL: SELECT `age` FROM `list_of_chinese_by_net_worth_2` WHERE `name` = 'Lucio Tan']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 05:42:57,003 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'birth_date' in 'where clause'")
[SQL: SELECT `senator` FROM `religious_affiliation_in_the_united_states_senate_10` WHERE `birth_date` = '1971-09-18']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-26 05:51:54,423 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'IATA' in 'field list'")
[SQL: SELECT `IATA` FROM `list_of_the_busiest_airports_in_brazil_0` WHERE `airport` = 'Presidente Juscelino Kubitschek International Airport']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 11:07:10,678 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'nationality' in 'field list'")
[SQL: SELECT `nationality` FROM `t_2004_united_states_grand_prix_0` WHERE `pos` = 4]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 13:04:50,994 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'nationality' in 'field list'")
[SQL: SELECT `nationality` FROM `t_2004_united_states_grand_prix_0` WHERE `driver` = 'Jenson Button']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 13:18:38,768 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1054, "Unknown column 'area' in 'field list'")
[SQL: SELECT `area` FROM `irish_sea_0` WHERE `county` = 'County Down']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 13:43:58,714 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1525, "Incorrect DATETIME value: '1:23.271'")
[SQL: SELECT `driver` FROM `t_1998_british_grand_prix_0` WHERE `lap` = '1:23.271']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 14:08:39,596 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1525, "Incorrect DATETIME value: '1:33.297'")
[SQL: SELECT `driver` FROM `t_2001_japanese_grand_prix_0` WHERE `lap` = '1:33.297']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 14:09:29,528 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1525, "Incorrect DATETIME value: '1:33.297'")
[SQL: SELECT `driver` FROM `t_2001_japanese_grand_prix_0` WHERE `lap` = '1:33.297']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 14:39:27,857 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'TableRAG.list_of_association_football_stadiums_by_country_6.stadium' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT `capacity`, `stadium`, `city` FROM `list_of_association_football_stadiums_by_country_6` GROUP BY `capacity`]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 14:44:56,060 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1525, "Incorrect DATETIME value: '1:19.440'")
[SQL: SELECT `driver` FROM `t_1999_canadian_grand_prix_0` WHERE `lap` = '1:19.440']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-28 14:46:31,357 - my_app - ERROR - SQL execution failed: (pymysql.err.OperationalError) (1525, "Incorrect DATETIME value: '1:19.440'")
[SQL: SELECT `driver` FROM `t_1999_canadian_grand_prix_0` WHERE `lap` = '1:19.440']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
